### PR TITLE
Modified zero-finding logic to support look angles.

### PR DESCRIPTION
**Pull request by dbookstaber**
Implemented look_angles for charting and added lines of interest.

Added Example.ipynb in root to demonstrate new functionality in two scenarios.

### CODE REVIEW

**Comment by o-murphy** [comment]
### Mostly look's good, but i have some questions

1. You don't need use calculate_elevation directly yet cause the interface's `__post_init__` 
already calls it
image
image
that's enough:
calc = Calculator(weapon, ammo)
zero_elevation = calc.elevation

2. You added the weapon to the HitResult attributes
so you don't need to put the `calc.weapon.zero_look_angle` directly to danger_space(), use it in the danger_space by "self."
```danger_space = shot_result.danger_space(Distance.Yard(300), Distance.Meter(.5), calc.weapon.zero_look_angle)```

3. I still to not understand why we are setting look angle to the weapon instead of the shot.The weapon zeroing mostly at 0 degree angle (target's altitude is close to shooter's). But the shot can have any. So zeroing once, we have to be able to calculate trajectory for the shots with different target's altitude (not for the weapon i mean)

**Comment by dbookstaber** [comment]
> 3. I still to not understand why we are setting look angle to the weapon instead of the shot. The weapon zeroing mostly at 0 degree angle (target's altitude is close to shooter's). But the shot can have any. So zeroing once, we have to be able to calculate trajectory for the shots with different target's altitude (not for the weapon i mean)

Yes, we should refactor this:

The parameters we should associate with the weapon are (A) sight_height and (B) zero_elevation, which is the barrel elevation relative to the sight line when the sight is zeroed.  (Note that to _establish_ the zero_elevation the shooter has to be able to say what the point of impact is for one specific shot at one specific distance.  Typically this is done on a controlled range, so look_angle = 0.  With sights that support one-shot zero it can be done in the field so it can be necessary to incorporate the look-angle in that case.  But in every case that's a characteristic of the shot that established the zero, not the weapon setup.)

Then characteristics associated with a shot are:

- look_angle – which is the angle of the sight line relative to horizontal
- relative_angle – which is an adjustment of the barrel angle relative to the zero_elevation caused by shooter holding or dialing the sight relative to its zero.

Then the barrel_elevation for the shot = zero_elevation + relative_angle + look_angle

**Comment by o-murphy** [comment]
I have to review it, so I'll do it next week

**Comment by o-murphy** [comment]
Amsing, very good job. I'll fix some issues in UnitPropsDict and daploy it. Also I'll add some fix to chart view

**Pull request merged**
